namespace yata
{
	partial class FontPickerForm
	{
		/// <summary>
		/// Designer variable used to keep track of non-visual components.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		private System.Windows.Forms.ListBox list_Font;
		private System.Windows.Forms.Button btn_Ok;
		private System.Windows.Forms.Button btn_Apply;
		private System.Windows.Forms.Button btn_Cancel;
		private System.Windows.Forms.Label lbl_Font;
		private System.Windows.Forms.Label lbl_Style;
		private System.Windows.Forms.Label lbl_Size;
		private System.Windows.Forms.ListBox list_Style;
		private System.Windows.Forms.ListBox list_Size;
		private System.Windows.Forms.Label lbl_Example;
		private System.Windows.Forms.TextBox tb_Size;
		private System.Windows.Forms.Panel panel1;

		/// <summary>
		/// Disposes resources used by the form.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && components != null)
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

/*		The designer is going to delete this, copy it back into InitializeComponent().

			this.lb_Font = new yata.FontListBox();
*/
		/// <summary>
		/// This method is required for Windows Forms designer support.
		/// Do not change the method contents inside the source code editor. The Forms designer might
		/// not be able to load this method if it was changed manually.
		/// </summary>
		private void InitializeComponent()
		{
			this.list_Font = new System.Windows.Forms.ListBox();
			this.btn_Ok = new System.Windows.Forms.Button();
			this.btn_Apply = new System.Windows.Forms.Button();
			this.btn_Cancel = new System.Windows.Forms.Button();
			this.lbl_Font = new System.Windows.Forms.Label();
			this.lbl_Style = new System.Windows.Forms.Label();
			this.lbl_Size = new System.Windows.Forms.Label();
			this.list_Style = new System.Windows.Forms.ListBox();
			this.list_Size = new System.Windows.Forms.ListBox();
			this.lbl_Example = new System.Windows.Forms.Label();
			this.tb_Size = new System.Windows.Forms.TextBox();
			this.panel1 = new System.Windows.Forms.Panel();
			this.panel1.SuspendLayout();
			this.SuspendLayout();
			// 
			// list_Font
			// 
			this.list_Font.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
			this.list_Font.FormattingEnabled = true;
			this.list_Font.ItemHeight = 20;
			this.list_Font.Items.AddRange(new object[] {
			new System.Drawing.Font("$Five Double Zero", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("18thCentury", 10F),
			new System.Drawing.Font("1979", 10F),
			new System.Drawing.Font("20th Century Font", 10F),
			new System.Drawing.Font("814yzx", 10F),
			new System.Drawing.Font("Abaddon™", 10F),
			new System.Drawing.Font("Abadi MT Condensed Extra Bold", 10F),
			new System.Drawing.Font("Abadi MT Condensed Light", 10F),
			new System.Drawing.Font("Abduction", 10F),
			new System.Drawing.Font("AC", 10F),
			new System.Drawing.Font("Acadian™", 10F),
			new System.Drawing.Font("Accords", 10F),
			new System.Drawing.Font("AdineKirnberg-Script", 10F),
			new System.Drawing.Font("Adorable", 10F),
			new System.Drawing.Font("Aharoni", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("Alchemy", 10F),
			new System.Drawing.Font("Alef", 10F),
			new System.Drawing.Font("Alexa", 10F, System.Drawing.FontStyle.Italic),
			new System.Drawing.Font("Alexandria-Medi", 10F),
			new System.Drawing.Font("AlfredDrake", 10F),
			new System.Drawing.Font("Algeria", 10F),
			new System.Drawing.Font("Algerian", 10F),
			new System.Drawing.Font("Allembert™", 10F),
			new System.Drawing.Font("Almanac MT", 10F),
			new System.Drawing.Font("Amazone BT", 10F),
			new System.Drawing.Font("Ambrosia", 10F),
			new System.Drawing.Font("Amelia BT", 10F),
			new System.Drawing.Font("AmericanText BT", 10F),
			new System.Drawing.Font("Amiri", 10F),
			new System.Drawing.Font("Amiri Quran", 10F),
			new System.Drawing.Font("AncientScript", 10F),
			new System.Drawing.Font("Andalus", 10F),
			new System.Drawing.Font("Andes", 10F),
			new System.Drawing.Font("Aneirin", 10F),
			new System.Drawing.Font("Angelic War", 10F),
			new System.Drawing.Font("Angelus™", 10F),
			new System.Drawing.Font("Angerthas", 10F),
			new System.Drawing.Font("Angerthas Moria", 10F),
			new System.Drawing.Font("Angie Impressing", 10F),
			new System.Drawing.Font("Anglican", 10F),
			new System.Drawing.Font("AngloSaxon Runes", 10F),
			new System.Drawing.Font("AngloSaxon Runes-1", 10F),
			new System.Drawing.Font("AngloSaxon Runes-2", 10F),
			new System.Drawing.Font("Angsana New", 10F),
			new System.Drawing.Font("AngsanaUPC", 10F),
			new System.Drawing.Font("Anke Calligraphic FG", 10F),
			new System.Drawing.Font("Antique", 10F),
			new System.Drawing.Font("Aparajita", 10F),
			new System.Drawing.Font("Arabian", 10F),
			new System.Drawing.Font("Arabic Typesetting", 10F),
			new System.Drawing.Font("Architext", 10F),
			new System.Drawing.Font("ArchitextOneType", 10F),
			new System.Drawing.Font("Arcitectura", 10F),
			new System.Drawing.Font("Arial", 10F),
			new System.Drawing.Font("Arial Black", 10F),
			new System.Drawing.Font("Arial Narrow", 10F),
			new System.Drawing.Font("Aristocrat", 10F),
			new System.Drawing.Font("Arrus Blk BT", 10F),
			new System.Drawing.Font("Arrus BT", 10F),
			new System.Drawing.Font("Arthur", 10F),
			new System.Drawing.Font("Asphodel™", 10F),
			new System.Drawing.Font("Asrafel", 10F),
			new System.Drawing.Font("Astro-SemiBold", 10F),
			new System.Drawing.Font("Babe-alicious", 10F),
			new System.Drawing.Font("Bach", 10F),
			new System.Drawing.Font("Baloney", 10F),
			new System.Drawing.Font("Baskerville-Normal", 10F),
			new System.Drawing.Font("Basque Light", 10F),
			new System.Drawing.Font("Batang", 10F),
			new System.Drawing.Font("BatangChe", 10F),
			new System.Drawing.Font("Bavand", 10F),
			new System.Drawing.Font("Bazooka", 10F),
			new System.Drawing.Font("Beesknees ITC", 10F),
			new System.Drawing.Font("Beffle", 10F),
			new System.Drawing.Font("Bell MT", 10F),
			new System.Drawing.Font("BellBottom.Laser", 10F),
			new System.Drawing.Font("Benguiat Bk BT", 10F),
			new System.Drawing.Font("Benjamin", 10F),
			new System.Drawing.Font("BenjaminCaps Caps:001.001", 10F),
			new System.Drawing.Font("BernhardMod BT", 10F),
			new System.Drawing.Font("BetterHeather", 10F),
			new System.Drawing.Font("Big City", 10F),
			new System.Drawing.Font("Big Fish Ensemble", 10F),
			new System.Drawing.Font("Billboard", 10F),
			new System.Drawing.Font("Black Chancery", 10F),
			new System.Drawing.Font("BlackChancery", 10F),
			new System.Drawing.Font("BlackChancery Regular", 10F),
			new System.Drawing.Font("Blackletter686 BT", 10F),
			new System.Drawing.Font("Bodacious", 10F),
			new System.Drawing.Font("Bodacious-Normal", 10F),
			new System.Drawing.Font("Bodoni-Bold", 10F),
			new System.Drawing.Font("Bodoni-Normal", 10F),
			new System.Drawing.Font("Bodoni-Normal-Italic", 10F),
			new System.Drawing.Font("Book Antiqua", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("Book Jacket", 10F),
			new System.Drawing.Font("Bookman Old Style", 10F),
			new System.Drawing.Font("Bookshelf Symbol 1", 10F),
			new System.Drawing.Font("Bookshelf Symbol 2", 10F),
			new System.Drawing.Font("Bookshelf Symbol 3", 10F),
			new System.Drawing.Font("Bordeaux Medium", 10F),
			new System.Drawing.Font("Borzoi", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("Botanical", 10F),
			new System.Drawing.Font("Bottled Fart", 10F),
			new System.Drawing.Font("Boulder", 10F),
			new System.Drawing.Font("Browallia New", 10F),
			new System.Drawing.Font("BrowalliaUPC", 10F),
			new System.Drawing.Font("Bruges™", 10F),
			new System.Drawing.Font("Brush738 BT", 10F),
			new System.Drawing.Font("Brushcut", 10F),
			new System.Drawing.Font("BrushStroke", 10F),
			new System.Drawing.Font("Caladea", 10F),
			new System.Drawing.Font("Calibri", 10F),
			new System.Drawing.Font("Calibri Light", 10F),
			new System.Drawing.Font("Caliph", 10F),
			new System.Drawing.Font("Calligraph810 BT", 10F),
			new System.Drawing.Font("Calligrapher", 10F),
			new System.Drawing.Font("Camberic", 10F),
			new System.Drawing.Font("Cambria", 10F),
			new System.Drawing.Font("Cambria Math", 10F),
			new System.Drawing.Font("Candara", 10F),
			new System.Drawing.Font("Candy Sniper", 10F),
			new System.Drawing.Font("Canker Sore", 10F),
			new System.Drawing.Font("Carleton", 10F),
			new System.Drawing.Font("Carlito", 10F),
			new System.Drawing.Font("Carolus", 10F),
			new System.Drawing.Font("Cascade-Light", 10F),
			new System.Drawing.Font("CaslonOpnface BT", 10F),
			new System.Drawing.Font("Casque OpenFace", 10F),
			new System.Drawing.Font("Celtic", 10F),
			new System.Drawing.Font("Celtic Garamond the 2nd", 10F),
			new System.Drawing.Font("Celticmd", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("Century Schoolbook", 10F),
			new System.Drawing.Font("Charlesworth", 10F),
			new System.Drawing.Font("Chaucer", 10F),
			new System.Drawing.Font("Chemistry", 10F),
			new System.Drawing.Font("Chinacat", 10F),
			new System.Drawing.Font("Cincinnatus™", 10F),
			new System.Drawing.Font("Columba", 10F),
			new System.Drawing.Font("Comic Sans MS", 10F),
			new System.Drawing.Font("Comix Heavy", 10F),
			new System.Drawing.Font("Confusebox", 10F),
			new System.Drawing.Font("Consolas", 10F),
			new System.Drawing.Font("Constantia", 10F),
			new System.Drawing.Font("Copperplate Gothic Bold", 10F),
			new System.Drawing.Font("Copperplate Gothic Light", 10F),
			new System.Drawing.Font("CopprplGoth Bd BT", 10F),
			new System.Drawing.Font("CopprplGoth BdCn BT", 10F),
			new System.Drawing.Font("CopprplGoth BT", 10F),
			new System.Drawing.Font("CopprplGoth Cn BT", 10F),
			new System.Drawing.Font("CopprplGoth Hv BT", 10F),
			new System.Drawing.Font("Corbel", 10F),
			new System.Drawing.Font("Cordia New", 10F),
			new System.Drawing.Font("CordiaUPC", 10F),
			new System.Drawing.Font("Courier New", 10F),
			new System.Drawing.Font("Creepygirl", 10F),
			new System.Drawing.Font("Cricket", 10F),
			new System.Drawing.Font("CuneiFont", 10F),
			new System.Drawing.Font("Cypriot", 10F),
			new System.Drawing.Font("Daniela", 10F),
			new System.Drawing.Font("Darrians Sexy Silhouettes 2", 10F),
			new System.Drawing.Font("Darrians Sexy Silhouettes 3", 10F),
			new System.Drawing.Font("Darrians Sexy Silhouettes 4", 10F),
			new System.Drawing.Font("Darrians Sexy Silouettes", 10F),
			new System.Drawing.Font("DaunPenh", 10F),
			new System.Drawing.Font("David", 10F),
			new System.Drawing.Font("David CLM", 10F),
			new System.Drawing.Font("David Libre", 10F),
			new System.Drawing.Font("Davida Bd BT", 10F),
			new System.Drawing.Font("Deities", 10F),
			new System.Drawing.Font("DejaVu Math TeX Gyre", 10F),
			new System.Drawing.Font("DejaVu Sans", 10F),
			new System.Drawing.Font("DejaVu Sans Condensed", 10F),
			new System.Drawing.Font("DejaVu Sans Light", 10F),
			new System.Drawing.Font("DejaVu Sans Mono", 10F),
			new System.Drawing.Font("DejaVu Serif", 10F),
			new System.Drawing.Font("DejaVu Serif Condensed", 10F),
			new System.Drawing.Font("Deusex", 10F),
			new System.Drawing.Font("DFKai-SB", 10F),
			new System.Drawing.Font("Dickens", 10F),
			new System.Drawing.Font("DilleniaUPC", 10F),
			new System.Drawing.Font("DokChampa", 10F),
			new System.Drawing.Font("Dolmen", 10F),
			new System.Drawing.Font("Dolphian", 10F),
			new System.Drawing.Font("Dotum", 10F),
			new System.Drawing.Font("DotumChe", 10F),
			new System.Drawing.Font("DownWind", 10F),
			new System.Drawing.Font("Dragon", 10F),
			new System.Drawing.Font("Dubiel", 10F),
			new System.Drawing.Font("Dupree", 10F),
			new System.Drawing.Font("Durrow", 10F),
			new System.Drawing.Font("EastGanglia", 10F),
			new System.Drawing.Font("Ebrima", 10F),
			new System.Drawing.Font("Edda", 10F),
			new System.Drawing.Font("Elbjorg", 10F),
			new System.Drawing.Font("ElGar", 10F),
			new System.Drawing.Font("ElGarrett", 10F),
			new System.Drawing.Font("Elphinstone™", 10F),
			new System.Drawing.Font("Eltic", 10F),
			new System.Drawing.Font("Embassy BT", 10F),
			new System.Drawing.Font("Emboss", 10F),
			new System.Drawing.Font("EmojiOne Color", 10F),
			new System.Drawing.Font("Enchanted Prairie Dog", 10F),
			new System.Drawing.Font("Encino", 10F),
			new System.Drawing.Font("English", 10F),
			new System.Drawing.Font("EngraversGothic BT", 10F),
			new System.Drawing.Font("Engrossing™", 10F),
			new System.Drawing.Font("EngrvrsOldEng BT", 10F),
			new System.Drawing.Font("Eras", 10F),
			new System.Drawing.Font("Esperanza™", 10F),
			new System.Drawing.Font("Estrangelo Edessa", 10F),
			new System.Drawing.Font("EucrosiaUPC", 10F),
			new System.Drawing.Font("Euphemia", 10F),
			new System.Drawing.Font("Excalibur Logotype", 10F),
			new System.Drawing.Font("Excalibur Monospace", 10F),
			new System.Drawing.Font("Excalibur Script", 10F),
			new System.Drawing.Font("Exocet", 10F),
			new System.Drawing.Font("Exocet Light ", 10F),
			new System.Drawing.Font("FangSong", 10F),
			new System.Drawing.Font("Fillmore", 10F),
			new System.Drawing.Font("First Grader", 10F),
			new System.Drawing.Font("FlemishScript BT", 10F),
			new System.Drawing.Font("Foxscript", 10F),
			new System.Drawing.Font("Frank Ruehl CLM", 10F),
			new System.Drawing.Font("Franklin Gothic", 10F),
			new System.Drawing.Font("Franklin Gothic Medium", 10F),
			new System.Drawing.Font("FrankRuehl", 10F),
			new System.Drawing.Font("Freefrm710 BT", 10F),
			new System.Drawing.Font("Freefrm721 Blk BT", 10F),
			new System.Drawing.Font("Freefrm721 BT", 10F),
			new System.Drawing.Font("Freehand521 BT", 10F),
			new System.Drawing.Font("Freehand575 BT", 10F),
			new System.Drawing.Font("Freehand591 BT", 10F),
			new System.Drawing.Font("FreesiaUPC", 10F),
			new System.Drawing.Font("Freestyle Script", 10F),
			new System.Drawing.Font("Fruity Drink", 10F),
			new System.Drawing.Font("Gabriel Regular Demo", 10F),
			new System.Drawing.Font("Gabriola", 10F),
			new System.Drawing.Font("Galaxia", 10F),
			new System.Drawing.Font("Gallery", 10F),
			new System.Drawing.Font("Gando BT", 10F),
			new System.Drawing.Font("Garamond", 10F),
			new System.Drawing.Font("Garamond Regular", 10F),
			new System.Drawing.Font("Gautami", 10F),
			new System.Drawing.Font("Gentium Basic", 10F),
			new System.Drawing.Font("Gentium Book Basic", 10F),
			new System.Drawing.Font("Georgia", 10F),
			new System.Drawing.Font("GeoSlab703 Lt BT", 10F),
			new System.Drawing.Font("Gill Sans Condensed", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("Gill Sans MT", 10F),
			new System.Drawing.Font("Gill Sans MT Condensed", 10F),
			new System.Drawing.Font("Gill Sans Ultra Bold", 10F),
			new System.Drawing.Font("Gill Sans Ultra Bold Condensed", 10F),
			new System.Drawing.Font("Gimbutas", 10F),
			new System.Drawing.Font("Girls are Weird", 10F),
			new System.Drawing.Font("Gisha", 10F),
			new System.Drawing.Font("Gismonda", 10F),
			new System.Drawing.Font("Gjallarhorn", 10F),
			new System.Drawing.Font("Glue", 10F),
			new System.Drawing.Font("Good Bad Ugly", 10F),
			new System.Drawing.Font("Goudy Old Style ATT", 10F),
			new System.Drawing.Font("Grail Light", 10F),
			new System.Drawing.Font("Graphic", 10F),
			new System.Drawing.Font("Graphite Light ATT", 10F),
			new System.Drawing.Font("Graphite Light Narrow ATT", 10F),
			new System.Drawing.Font("Griffin", 10F),
			new System.Drawing.Font("Gulim", 10F),
			new System.Drawing.Font("GulimChe", 10F),
			new System.Drawing.Font("Gungsuh", 10F),
			new System.Drawing.Font("GungsuhChe", 10F),
			new System.Drawing.Font("Hadrianus Demo", 10F),
			new System.Drawing.Font("Haettenschweiler", 10F),
			new System.Drawing.Font("Halloween", 10F),
			new System.Drawing.Font("Haman", 10F),
			new System.Drawing.Font("HandScript", 10F),
			new System.Drawing.Font("Harrington", 10F),
			new System.Drawing.Font("Head Case", 10F),
			new System.Drawing.Font("Hieroglify", 10F),
			new System.Drawing.Font("High Tower Text", 10F),
			new System.Drawing.Font("HighNoon", 10F),
			new System.Drawing.Font("Hooteroll", 10F),
			new System.Drawing.Font("Hooteroll_Jam", 10F),
			new System.Drawing.Font("Horse", 10F),
			new System.Drawing.Font("Humanst521 Cn BT", 10F),
			new System.Drawing.Font("Humanst521 Lt BT", 10F),
			new System.Drawing.Font("Iglesia-Light", 10F),
			new System.Drawing.Font("Ignacio", 10F),
			new System.Drawing.Font("Impact", 10F),
			new System.Drawing.Font("Impress BT", 10F),
			new System.Drawing.Font("Imprint MT Shadow", 10F),
			new System.Drawing.Font("Impuls BT", 10F),
			new System.Drawing.Font("Inspiration", 10F),
			new System.Drawing.Font("IrisUPC", 10F),
			new System.Drawing.Font("Iskoola Pota", 10F),
			new System.Drawing.Font("JasmineUPC", 10F),
			new System.Drawing.Font("Jellyka BeesAntique Handwriting", 10F),
			new System.Drawing.Font("Jellyka End_less Voyage", 10F),
			new System.Drawing.Font("Jellyka Saint-Andrew\'s Queen", 10F),
			new System.Drawing.Font("Jellyka Wonderland Wine", 10F),
			new System.Drawing.Font("Jolt", 10F),
			new System.Drawing.Font("Judas", 10F),
			new System.Drawing.Font("Juergen", 10F),
			new System.Drawing.Font("Jugend", 10F),
			new System.Drawing.Font("Juliet", 10F),
			new System.Drawing.Font("Junior & Stinky", 10F),
			new System.Drawing.Font("KacstBook", 10F),
			new System.Drawing.Font("KacstOffice", 10F),
			new System.Drawing.Font("KaiTi", 10F),
			new System.Drawing.Font("Kaligraf Latin", 10F),
			new System.Drawing.Font("Kalinga", 10F),
			new System.Drawing.Font("Kartika", 10F),
			new System.Drawing.Font("Kashmir", 10F),
			new System.Drawing.Font("Kaste", 10F),
			new System.Drawing.Font("Kastellar", 10F),
			new System.Drawing.Font("Keystrokes MT", 10F),
			new System.Drawing.Font("Khmer UI", 10F),
			new System.Drawing.Font("Klingon", 10F),
			new System.Drawing.Font("KodchiangUPC", 10F),
			new System.Drawing.Font("Kokila", 10F),
			new System.Drawing.Font("Kool", 10F),
			new System.Drawing.Font("Kroeburn", 10F),
			new System.Drawing.Font("Lao UI", 10F),
			new System.Drawing.Font("LaPointe\'s Road", 10F),
			new System.Drawing.Font("Last Ninja", 10F),
			new System.Drawing.Font("Latha", 10F),
			new System.Drawing.Font("Leelawadee", 10F),
			new System.Drawing.Font("Letter Gothic Line", 10F),
			new System.Drawing.Font("Letterman-Solid", 10F),
			new System.Drawing.Font("Levenim MT", 10F),
			new System.Drawing.Font("Liberation Mono", 10F),
			new System.Drawing.Font("Liberation Sans", 10F),
			new System.Drawing.Font("Liberation Sans Narrow", 10F),
			new System.Drawing.Font("Liberation Serif", 10F),
			new System.Drawing.Font("Libra BT", 10F),
			new System.Drawing.Font("Librarian", 10F),
			new System.Drawing.Font("Liddie Black", 10F),
			new System.Drawing.Font("Lights", 10F),
			new System.Drawing.Font("LilyUPC", 10F),
			new System.Drawing.Font("Linux Biolinum G", 10F),
			new System.Drawing.Font("Linux Libertine Display G", 10F),
			new System.Drawing.Font("Linux Libertine G", 10F),
			new System.Drawing.Font("LLUmbrian", 10F),
			new System.Drawing.Font("LLVenetic", 10F),
			new System.Drawing.Font("Loki Cola", 10F),
			new System.Drawing.Font("LotusWP Box", 10F),
			new System.Drawing.Font("LotusWP Icon", 10F),
			new System.Drawing.Font("LotusWP Int A", 10F),
			new System.Drawing.Font("LotusWP Int B", 10F),
			new System.Drawing.Font("LotusWP Type", 10F),
			new System.Drawing.Font("Lucida Blacklet", 10F),
			new System.Drawing.Font("Lucida Calligraphy", 10F),
			new System.Drawing.Font("Lucida Console", 10F),
			new System.Drawing.Font("Lucida Sans Unicode", 10F),
			new System.Drawing.Font("Luxembourg", 10F),
			new System.Drawing.Font("Machiavelli", 10F),
			new System.Drawing.Font("MacHumaine", 10F),
			new System.Drawing.Font("Magik", 10F),
			new System.Drawing.Font("Maiandra GD", 10F),
			new System.Drawing.Font("Malgun Gothic", 10F),
			new System.Drawing.Font("Mangal", 10F),
			new System.Drawing.Font("Maple Serum", 10F),
			new System.Drawing.Font("Mapmaker Thin", 10F),
			new System.Drawing.Font("MarkerFeltThin", 10F),
			new System.Drawing.Font("MarkerFeltWide-Plain", 10F),
			new System.Drawing.Font("Marlett", 10F),
			new System.Drawing.Font("Marquee", 10F),
			new System.Drawing.Font("Matura MT Script Capitals", 10F),
			new System.Drawing.Font("Mcgannahan", 10F),
			new System.Drawing.Font("Medusa", 10F),
			new System.Drawing.Font("Meet John Henry", 10F),
			new System.Drawing.Font("Meiryo", 10F),
			new System.Drawing.Font("Meiryo UI", 10F),
			new System.Drawing.Font("Men In Black Credits", 10F),
			new System.Drawing.Font("Mephisto™", 10F),
			new System.Drawing.Font("Microsoft Himalaya", 10F),
			new System.Drawing.Font("Microsoft JhengHei", 10F),
			new System.Drawing.Font("Microsoft New Tai Lue", 10F),
			new System.Drawing.Font("Microsoft PhagsPa", 10F),
			new System.Drawing.Font("Microsoft Sans Serif", 10F),
			new System.Drawing.Font("Microsoft Tai Le", 10F),
			new System.Drawing.Font("Microsoft Uighur", 10F),
			new System.Drawing.Font("Microsoft YaHei", 10F),
			new System.Drawing.Font("Microsoft Yi Baiti", 10F),
			new System.Drawing.Font("MingLiU", 10F),
			new System.Drawing.Font("MingLiU-ExtB", 10F),
			new System.Drawing.Font("MingLiU_HKSCS", 10F),
			new System.Drawing.Font("MingLiU_HKSCS-ExtB", 10F),
			new System.Drawing.Font("Minstrel Script", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("Miriam", 10F),
			new System.Drawing.Font("Miriam CLM", 10F),
			new System.Drawing.Font("Miriam Fixed", 10F),
			new System.Drawing.Font("Miriam Mono CLM", 10F),
			new System.Drawing.Font("MisterEarl BT", 10F),
			new System.Drawing.Font("Mitzvah", 10F),
			new System.Drawing.Font("Monaco", 10F),
			new System.Drawing.Font("Mongolian Baiti", 10F),
			new System.Drawing.Font("Monkey Chunks", 10F),
			new System.Drawing.Font("Monotype Sorts", 10F),
			new System.Drawing.Font("MoolBoran", 10F),
			new System.Drawing.Font("Mordred", 10F),
			new System.Drawing.Font("More Enchanted Prairie Dog", 10F),
			new System.Drawing.Font("Morpheus", 10F),
			new System.Drawing.Font("MS Gothic", 10F),
			new System.Drawing.Font("MS Mincho", 10F),
			new System.Drawing.Font("MS Outlook", 10F),
			new System.Drawing.Font("MS PGothic", 10F),
			new System.Drawing.Font("MS PMincho", 10F),
			new System.Drawing.Font("MS UI Gothic", 10F),
			new System.Drawing.Font("Mutlu", 10F),
			new System.Drawing.Font("MV Boli", 10F),
			new System.Drawing.Font("Narkisim", 10F),
			new System.Drawing.Font("Nauert", 10F),
			new System.Drawing.Font("Neone", 10F),
			new System.Drawing.Font("Neverwinter", 10F),
			new System.Drawing.Font("Nite", 10F),
			new System.Drawing.Font("Nixon", 10F),
			new System.Drawing.Font("Nosfer", 10F),
			new System.Drawing.Font("Nosferatu", 10F, System.Drawing.FontStyle.Italic),
			new System.Drawing.Font("Nosferotica", 10F),
			new System.Drawing.Font("Noto Kufi Arabic", 10F),
			new System.Drawing.Font("Noto Mono", 10F),
			new System.Drawing.Font("Noto Naskh Arabic", 10F),
			new System.Drawing.Font("Noto Naskh Arabic UI", 10F),
			new System.Drawing.Font("Noto Sans", 10F),
			new System.Drawing.Font("Noto Sans Arabic", 10F),
			new System.Drawing.Font("Noto Sans Arabic UI", 10F),
			new System.Drawing.Font("Noto Sans Armenian", 10F),
			new System.Drawing.Font("Noto Sans Cond", 10F),
			new System.Drawing.Font("Noto Sans Georgian", 10F),
			new System.Drawing.Font("Noto Sans Hebrew", 10F),
			new System.Drawing.Font("Noto Sans Lao", 10F),
			new System.Drawing.Font("Noto Sans Light", 10F),
			new System.Drawing.Font("Noto Sans Lisu", 10F),
			new System.Drawing.Font("Noto Serif", 10F),
			new System.Drawing.Font("Noto Serif Armenian", 10F),
			new System.Drawing.Font("Noto Serif Cond", 10F),
			new System.Drawing.Font("Noto Serif Georgian", 10F),
			new System.Drawing.Font("Noto Serif Hebrew", 10F),
			new System.Drawing.Font("Noto Serif Lao", 10F),
			new System.Drawing.Font("Noto Serif Light", 10F),
			new System.Drawing.Font("Nouveau", 10F),
			new System.Drawing.Font("NSimSun", 10F),
			new System.Drawing.Font("Nuptial BT", 10F),
			new System.Drawing.Font("Nyala", 10F),
			new System.Drawing.Font("OFL Sorts Mill Goudy TT", 10F),
			new System.Drawing.Font("Ogilvie", 10F),
			new System.Drawing.Font("Old English Gothic", 10F),
			new System.Drawing.Font("Old printing press_FREE-version", 10F),
			new System.Drawing.Font("Olde English", 10F),
			new System.Drawing.Font("Onyx BT", 10F),
			new System.Drawing.Font("Open Sans", 10F),
			new System.Drawing.Font("OpenSymbol", 10F),
			new System.Drawing.Font("OptimusPrinceps", 10F),
			new System.Drawing.Font("OptimusPrincepsSemiBold", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("Oscan", 10F),
			new System.Drawing.Font("OzHandicraft BT", 10F),
			new System.Drawing.Font("P", 10F),
			new System.Drawing.Font("Palatia", 10F),
			new System.Drawing.Font("Palatino Linotype", 10F),
			new System.Drawing.Font("Paramount", 10F),
			new System.Drawing.Font("Paris", 10F),
			new System.Drawing.Font("Patrician™", 10F),
			new System.Drawing.Font("PCMIra", 10F),
			new System.Drawing.Font("Peace", 10F),
			new System.Drawing.Font("Penyae", 10F),
			new System.Drawing.Font("Piranesi It BT", 10F),
			new System.Drawing.Font("Plantagenet Cherokee", 10F),
			new System.Drawing.Font("Platthand Demo", 10F),
			new System.Drawing.Font("Plok", 10F),
			new System.Drawing.Font("PMingLiU", 10F),
			new System.Drawing.Font("PMingLiU-ExtB", 10F),
			new System.Drawing.Font("Poison Dots", 10F),
			new System.Drawing.Font("Poke", 10F),
			new System.Drawing.Font("Poncho", 10F),
			new System.Drawing.Font("PonchoVia-Light", 10F),
			new System.Drawing.Font("Pontifica Demo", 10F),
			new System.Drawing.Font("PotsDam", 10F),
			new System.Drawing.Font("Powderworks BRK", 10F),
			new System.Drawing.Font("Present-Normal", 10F),
			new System.Drawing.Font("Priory", 10F),
			new System.Drawing.Font("Promenade", 10F),
			new System.Drawing.Font("Pseudolux", 10F),
			new System.Drawing.Font("Psychadelic", 10F),
			new System.Drawing.Font("PT Serif", 10F),
			new System.Drawing.Font("Pyxidium Quick", 10F),
			new System.Drawing.Font("Quantity", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("QuartetBold", 10F),
			new System.Drawing.Font("QuartetRegular", 10F),
			new System.Drawing.Font("Quetzal Demo", 10F),
			new System.Drawing.Font("Raavi", 10F),
			new System.Drawing.Font("Radius", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("Reed", 10F),
			new System.Drawing.Font("Reem Kufi", 10F),
			new System.Drawing.Font("Ribbon131 Bd BT", 10F),
			new System.Drawing.Font("Rickshaw", 10F),
			new System.Drawing.Font("Rod", 10F),
			new System.Drawing.Font("Rogers", 10F),
			new System.Drawing.Font("Roman Stonecut", 10F),
			new System.Drawing.Font("Romeodn", 10F),
			new System.Drawing.Font("RoostHeavy", 10F),
			new System.Drawing.Font("Roughwork Demo", 10F),
			new System.Drawing.Font("Rounders", 10F),
			new System.Drawing.Font("Rubik", 10F),
			new System.Drawing.Font("Rudelsberg", 10F),
			new System.Drawing.Font("Sakkal Majalla", 10F),
			new System.Drawing.Font("SANTOS DUMONT", 10F),
			new System.Drawing.Font("Sanvito", 10F, System.Drawing.FontStyle.Italic),
			new System.Drawing.Font("Scheherazade", 10F),
			new System.Drawing.Font("Schoolbook", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("SchoolBoy", 10F),
			new System.Drawing.Font("Science Project", 10F),
			new System.Drawing.Font("Scriptina", 10F),
			new System.Drawing.Font("Scriptina - Alternates", 10F),
			new System.Drawing.Font("Seagull Lt BT", 10F),
			new System.Drawing.Font("Seagull Md BT", 10F),
			new System.Drawing.Font("Segoe Print", 10F),
			new System.Drawing.Font("Segoe Script", 10F),
			new System.Drawing.Font("Segoe UI", 10F),
			new System.Drawing.Font("Segoe UI Light", 10F),
			new System.Drawing.Font("Segoe UI Semibold", 10F),
			new System.Drawing.Font("Segoe UI Symbol", 10F),
			new System.Drawing.Font("Seven Swordsmen BB", 10F),
			new System.Drawing.Font("Sexy Silouette Stencils", 10F),
			new System.Drawing.Font("SEXY SPANISH ERASMUS GIRLS V.2.", 10F),
			new System.Drawing.Font("SEXY_SPANISH_WOMAN", 10F),
			new System.Drawing.Font("ShelleyAllegro BT", 10F),
			new System.Drawing.Font("ShelleyAndante BT", 10F),
			new System.Drawing.Font("ShelleyVolante BT", 10F),
			new System.Drawing.Font("Sherwood", 10F),
			new System.Drawing.Font("Shonar Bangla", 10F),
			new System.Drawing.Font("Shruti", 10F),
			new System.Drawing.Font("SimHei", 10F),
			new System.Drawing.Font("Simplified Arabic", 10F),
			new System.Drawing.Font("Simplified Arabic Fixed", 10F),
			new System.Drawing.Font("SimSun", 10F),
			new System.Drawing.Font("SimSun-ExtB", 10F),
			new System.Drawing.Font("Sinaloa", 10F),
			new System.Drawing.Font("Singothic", 10F),
			new System.Drawing.Font("Smegalomania", 10F),
			new System.Drawing.Font("Snell BT", 10F),
			new System.Drawing.Font("Source Code Pro", 10F),
			new System.Drawing.Font("Source Code Pro Black", 10F),
			new System.Drawing.Font("Source Code Pro ExtraLight", 10F),
			new System.Drawing.Font("Source Code Pro Light", 10F),
			new System.Drawing.Font("Source Code Pro Medium", 10F),
			new System.Drawing.Font("Source Code Pro Semibold", 10F),
			new System.Drawing.Font("Source Sans Pro", 10F),
			new System.Drawing.Font("Source Sans Pro Black", 10F),
			new System.Drawing.Font("Source Sans Pro ExtraLight", 10F),
			new System.Drawing.Font("Source Sans Pro Light", 10F),
			new System.Drawing.Font("Source Sans Pro Semibold", 10F),
			new System.Drawing.Font("Stencil", 10F),
			new System.Drawing.Font("Stencil-Normal", 10F),
			new System.Drawing.Font("Stencilcase", 10F),
			new System.Drawing.Font("Stinger", 10F),
			new System.Drawing.Font("Stonecross", 10F),
			new System.Drawing.Font("Stonehenge", 10F),
			new System.Drawing.Font("Styletto", 10F),
			new System.Drawing.Font("Sumdumgoi", 10F),
			new System.Drawing.Font("Swis721 BlkEx BT", 10F),
			new System.Drawing.Font("Sylfaen", 10F),
			new System.Drawing.Font("Symbol", 10F),
			new System.Drawing.Font("Tahoma", 10F),
			new System.Drawing.Font("Tango", 10F),
			new System.Drawing.Font("Tapestry", 10F),
			new System.Drawing.Font("Tarantis", 10F),
			new System.Drawing.Font("Tempo", 10F),
			new System.Drawing.Font("Tempus", 10F),
			new System.Drawing.Font("Tengwar Cursive", 10F),
			new System.Drawing.Font("Tengwar Noldor", 10F),
			new System.Drawing.Font("Tengwar Noldor-1", 10F),
			new System.Drawing.Font("Tengwar Noldor-2", 10F),
			new System.Drawing.Font("Tengwar Noldor-A", 10F),
			new System.Drawing.Font("Tengwar Parmaite", 10F),
			new System.Drawing.Font("Tengwar Quenya", 10F),
			new System.Drawing.Font("Tengwar Quenya-1", 10F),
			new System.Drawing.Font("Tengwar Quenya-2", 10F),
			new System.Drawing.Font("Tengwar Quenya-A", 10F),
			new System.Drawing.Font("Tengwar Sindarin", 10F),
			new System.Drawing.Font("Tengwar Sindarin-1", 10F),
			new System.Drawing.Font("Tengwar Sindarin-2", 10F),
			new System.Drawing.Font("Tengwar Sindarin-A", 10F),
			new System.Drawing.Font("Tengwar-Gandalf", 10F),
			new System.Drawing.Font("Terpsichore™", 10F),
			new System.Drawing.Font("Thalia", 10F),
			new System.Drawing.Font("the King & Queen font", 10F),
			new System.Drawing.Font("This is not a font", 10F),
			new System.Drawing.Font("Thorass", 10F),
			new System.Drawing.Font("Times New Roman", 10F),
			new System.Drawing.Font("Totem", 10F),
			new System.Drawing.Font("ToulouseLautrec", 10F),
			new System.Drawing.Font("Traditional Arabic", 10F),
			new System.Drawing.Font("Trebuchet MS", 10F),
			new System.Drawing.Font("Tribune", 10F),
			new System.Drawing.Font("True Stories", 10F),
			new System.Drawing.Font("TrumpetLite", 10F),
			new System.Drawing.Font("Tunga", 10F),
			new System.Drawing.Font("Turkey Sandwich", 10F),
			new System.Drawing.Font("Typewriter", 10F),
			new System.Drawing.Font("Uncials", 10F),
			new System.Drawing.Font("Unispace", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("University", 10F),
			new System.Drawing.Font("UniversityRoman", 10F),
			new System.Drawing.Font("Unserif", 10F),
			new System.Drawing.Font("Upper-EastSide", 10F),
			new System.Drawing.Font("Urban Scrawl Chill", 10F),
			new System.Drawing.Font("Urban Scrawl Down", 10F),
			new System.Drawing.Font("Urban Scrawl-Buttah", 10F),
			new System.Drawing.Font("ureka", 10F),
			new System.Drawing.Font("Utsaah", 10F),
			new System.Drawing.Font("Valdemar", 10F),
			new System.Drawing.Font("Vani", 10F),
			new System.Drawing.Font("Vein", 10F),
			new System.Drawing.Font("Verdana", 10F),
			new System.Drawing.Font("Verticalization", 10F),
			new System.Drawing.Font("Vespasiano Demo", 10F),
			new System.Drawing.Font("Victorias-Secre", 10F),
			new System.Drawing.Font("Vijaya", 10F),
			new System.Drawing.Font("Viking", 10F),
			new System.Drawing.Font("Violation", 10F),
			new System.Drawing.Font("Vireo", 10F),
			new System.Drawing.Font("Vrinda", 10F),
			new System.Drawing.Font("Wanted Poster", 10F),
			new System.Drawing.Font("Webdings", 10F),
			new System.Drawing.Font("WeddingText BT", 10F),
			new System.Drawing.Font("Weirdo Warp", 10F),
			new System.Drawing.Font("Weiss", 10F),
			new System.Drawing.Font("Windsong", 10F),
			new System.Drawing.Font("Wingdings", 10F),
			new System.Drawing.Font("Xirwena", 10F),
			new System.Drawing.Font("Yataghan", 10F),
			new System.Drawing.Font("Zygoth", 10F),
			new System.Drawing.Font("Zyme", 10F, System.Drawing.FontStyle.Italic),
			new System.Drawing.Font("$Five Double Zero", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("18thCentury", 10F),
			new System.Drawing.Font("1979", 10F),
			new System.Drawing.Font("20th Century Font", 10F),
			new System.Drawing.Font("814yzx", 10F),
			new System.Drawing.Font("Abaddon™", 10F),
			new System.Drawing.Font("Abadi MT Condensed Extra Bold", 10F),
			new System.Drawing.Font("Abadi MT Condensed Light", 10F),
			new System.Drawing.Font("Abduction", 10F),
			new System.Drawing.Font("AC", 10F),
			new System.Drawing.Font("Acadian™", 10F),
			new System.Drawing.Font("Accords", 10F),
			new System.Drawing.Font("AdineKirnberg-Script", 10F),
			new System.Drawing.Font("Adorable", 10F),
			new System.Drawing.Font("Aharoni", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("Alchemy", 10F),
			new System.Drawing.Font("Alef", 10F),
			new System.Drawing.Font("Alexa", 10F, System.Drawing.FontStyle.Italic),
			new System.Drawing.Font("Alexandria-Medi", 10F),
			new System.Drawing.Font("AlfredDrake", 10F),
			new System.Drawing.Font("Algeria", 10F),
			new System.Drawing.Font("Algerian", 10F),
			new System.Drawing.Font("Allembert™", 10F),
			new System.Drawing.Font("Almanac MT", 10F),
			new System.Drawing.Font("Amazone BT", 10F),
			new System.Drawing.Font("Ambrosia", 10F),
			new System.Drawing.Font("Amelia BT", 10F),
			new System.Drawing.Font("AmericanText BT", 10F),
			new System.Drawing.Font("Amiri", 10F),
			new System.Drawing.Font("Amiri Quran", 10F),
			new System.Drawing.Font("AncientScript", 10F),
			new System.Drawing.Font("Andalus", 10F),
			new System.Drawing.Font("Andes", 10F),
			new System.Drawing.Font("Aneirin", 10F),
			new System.Drawing.Font("Angelic War", 10F),
			new System.Drawing.Font("Angelus™", 10F),
			new System.Drawing.Font("Angerthas", 10F),
			new System.Drawing.Font("Angerthas Moria", 10F),
			new System.Drawing.Font("Angie Impressing", 10F),
			new System.Drawing.Font("Anglican", 10F),
			new System.Drawing.Font("AngloSaxon Runes", 10F),
			new System.Drawing.Font("AngloSaxon Runes-1", 10F),
			new System.Drawing.Font("AngloSaxon Runes-2", 10F),
			new System.Drawing.Font("Angsana New", 10F),
			new System.Drawing.Font("AngsanaUPC", 10F),
			new System.Drawing.Font("Anke Calligraphic FG", 10F),
			new System.Drawing.Font("Antique", 10F),
			new System.Drawing.Font("Aparajita", 10F),
			new System.Drawing.Font("Arabian", 10F),
			new System.Drawing.Font("Arabic Typesetting", 10F),
			new System.Drawing.Font("Architext", 10F),
			new System.Drawing.Font("ArchitextOneType", 10F),
			new System.Drawing.Font("Arcitectura", 10F),
			new System.Drawing.Font("Arial", 10F),
			new System.Drawing.Font("Arial Black", 10F),
			new System.Drawing.Font("Arial Narrow", 10F),
			new System.Drawing.Font("Aristocrat", 10F),
			new System.Drawing.Font("Arrus Blk BT", 10F),
			new System.Drawing.Font("Arrus BT", 10F),
			new System.Drawing.Font("Arthur", 10F),
			new System.Drawing.Font("Asphodel™", 10F),
			new System.Drawing.Font("Asrafel", 10F),
			new System.Drawing.Font("Astro-SemiBold", 10F),
			new System.Drawing.Font("Babe-alicious", 10F),
			new System.Drawing.Font("Bach", 10F),
			new System.Drawing.Font("Baloney", 10F),
			new System.Drawing.Font("Baskerville-Normal", 10F),
			new System.Drawing.Font("Basque Light", 10F),
			new System.Drawing.Font("Batang", 10F),
			new System.Drawing.Font("BatangChe", 10F),
			new System.Drawing.Font("Bavand", 10F),
			new System.Drawing.Font("Bazooka", 10F),
			new System.Drawing.Font("Beesknees ITC", 10F),
			new System.Drawing.Font("Beffle", 10F),
			new System.Drawing.Font("Bell MT", 10F),
			new System.Drawing.Font("BellBottom.Laser", 10F),
			new System.Drawing.Font("Benguiat Bk BT", 10F),
			new System.Drawing.Font("Benjamin", 10F),
			new System.Drawing.Font("BenjaminCaps Caps:001.001", 10F),
			new System.Drawing.Font("BernhardMod BT", 10F),
			new System.Drawing.Font("BetterHeather", 10F),
			new System.Drawing.Font("Big City", 10F),
			new System.Drawing.Font("Big Fish Ensemble", 10F),
			new System.Drawing.Font("Billboard", 10F),
			new System.Drawing.Font("Black Chancery", 10F),
			new System.Drawing.Font("BlackChancery", 10F),
			new System.Drawing.Font("BlackChancery Regular", 10F),
			new System.Drawing.Font("Blackletter686 BT", 10F),
			new System.Drawing.Font("Bodacious", 10F),
			new System.Drawing.Font("Bodacious-Normal", 10F),
			new System.Drawing.Font("Bodoni-Bold", 10F),
			new System.Drawing.Font("Bodoni-Normal", 10F),
			new System.Drawing.Font("Bodoni-Normal-Italic", 10F),
			new System.Drawing.Font("Book Antiqua", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("Book Jacket", 10F),
			new System.Drawing.Font("Bookman Old Style", 10F),
			new System.Drawing.Font("Bookshelf Symbol 1", 10F),
			new System.Drawing.Font("Bookshelf Symbol 2", 10F),
			new System.Drawing.Font("Bookshelf Symbol 3", 10F),
			new System.Drawing.Font("Bordeaux Medium", 10F),
			new System.Drawing.Font("Borzoi", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("Botanical", 10F),
			new System.Drawing.Font("Bottled Fart", 10F),
			new System.Drawing.Font("Boulder", 10F),
			new System.Drawing.Font("Browallia New", 10F),
			new System.Drawing.Font("BrowalliaUPC", 10F),
			new System.Drawing.Font("Bruges™", 10F),
			new System.Drawing.Font("Brush738 BT", 10F),
			new System.Drawing.Font("Brushcut", 10F),
			new System.Drawing.Font("BrushStroke", 10F),
			new System.Drawing.Font("Caladea", 10F),
			new System.Drawing.Font("Calibri", 10F),
			new System.Drawing.Font("Calibri Light", 10F),
			new System.Drawing.Font("Caliph", 10F),
			new System.Drawing.Font("Calligraph810 BT", 10F),
			new System.Drawing.Font("Calligrapher", 10F),
			new System.Drawing.Font("Camberic", 10F),
			new System.Drawing.Font("Cambria", 10F),
			new System.Drawing.Font("Cambria Math", 10F),
			new System.Drawing.Font("Candara", 10F),
			new System.Drawing.Font("Candy Sniper", 10F),
			new System.Drawing.Font("Canker Sore", 10F),
			new System.Drawing.Font("Carleton", 10F),
			new System.Drawing.Font("Carlito", 10F),
			new System.Drawing.Font("Carolus", 10F),
			new System.Drawing.Font("Cascade-Light", 10F),
			new System.Drawing.Font("CaslonOpnface BT", 10F),
			new System.Drawing.Font("Casque OpenFace", 10F),
			new System.Drawing.Font("Celtic", 10F),
			new System.Drawing.Font("Celtic Garamond the 2nd", 10F),
			new System.Drawing.Font("Celticmd", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("Century Schoolbook", 10F),
			new System.Drawing.Font("Charlesworth", 10F),
			new System.Drawing.Font("Chaucer", 10F),
			new System.Drawing.Font("Chemistry", 10F),
			new System.Drawing.Font("Chinacat", 10F),
			new System.Drawing.Font("Cincinnatus™", 10F),
			new System.Drawing.Font("Columba", 10F),
			new System.Drawing.Font("Comic Sans MS", 10F),
			new System.Drawing.Font("Comix Heavy", 10F),
			new System.Drawing.Font("Confusebox", 10F),
			new System.Drawing.Font("Consolas", 10F),
			new System.Drawing.Font("Constantia", 10F),
			new System.Drawing.Font("Copperplate Gothic Bold", 10F),
			new System.Drawing.Font("Copperplate Gothic Light", 10F),
			new System.Drawing.Font("CopprplGoth Bd BT", 10F),
			new System.Drawing.Font("CopprplGoth BdCn BT", 10F),
			new System.Drawing.Font("CopprplGoth BT", 10F),
			new System.Drawing.Font("CopprplGoth Cn BT", 10F),
			new System.Drawing.Font("CopprplGoth Hv BT", 10F),
			new System.Drawing.Font("Corbel", 10F),
			new System.Drawing.Font("Cordia New", 10F),
			new System.Drawing.Font("CordiaUPC", 10F),
			new System.Drawing.Font("Courier New", 10F),
			new System.Drawing.Font("Creepygirl", 10F),
			new System.Drawing.Font("Cricket", 10F),
			new System.Drawing.Font("CuneiFont", 10F),
			new System.Drawing.Font("Cypriot", 10F),
			new System.Drawing.Font("Daniela", 10F),
			new System.Drawing.Font("Darrians Sexy Silhouettes 2", 10F),
			new System.Drawing.Font("Darrians Sexy Silhouettes 3", 10F),
			new System.Drawing.Font("Darrians Sexy Silhouettes 4", 10F),
			new System.Drawing.Font("Darrians Sexy Silouettes", 10F),
			new System.Drawing.Font("DaunPenh", 10F),
			new System.Drawing.Font("David", 10F),
			new System.Drawing.Font("David CLM", 10F),
			new System.Drawing.Font("David Libre", 10F),
			new System.Drawing.Font("Davida Bd BT", 10F),
			new System.Drawing.Font("Deities", 10F),
			new System.Drawing.Font("DejaVu Math TeX Gyre", 10F),
			new System.Drawing.Font("DejaVu Sans", 10F),
			new System.Drawing.Font("DejaVu Sans Condensed", 10F),
			new System.Drawing.Font("DejaVu Sans Light", 10F),
			new System.Drawing.Font("DejaVu Sans Mono", 10F),
			new System.Drawing.Font("DejaVu Serif", 10F),
			new System.Drawing.Font("DejaVu Serif Condensed", 10F),
			new System.Drawing.Font("Deusex", 10F),
			new System.Drawing.Font("DFKai-SB", 10F),
			new System.Drawing.Font("Dickens", 10F),
			new System.Drawing.Font("DilleniaUPC", 10F),
			new System.Drawing.Font("DokChampa", 10F),
			new System.Drawing.Font("Dolmen", 10F),
			new System.Drawing.Font("Dolphian", 10F),
			new System.Drawing.Font("Dotum", 10F),
			new System.Drawing.Font("DotumChe", 10F),
			new System.Drawing.Font("DownWind", 10F),
			new System.Drawing.Font("Dragon", 10F),
			new System.Drawing.Font("Dubiel", 10F),
			new System.Drawing.Font("Dupree", 10F),
			new System.Drawing.Font("Durrow", 10F),
			new System.Drawing.Font("EastGanglia", 10F),
			new System.Drawing.Font("Ebrima", 10F),
			new System.Drawing.Font("Edda", 10F),
			new System.Drawing.Font("Elbjorg", 10F),
			new System.Drawing.Font("ElGar", 10F),
			new System.Drawing.Font("ElGarrett", 10F),
			new System.Drawing.Font("Elphinstone™", 10F),
			new System.Drawing.Font("Eltic", 10F),
			new System.Drawing.Font("Embassy BT", 10F),
			new System.Drawing.Font("Emboss", 10F),
			new System.Drawing.Font("EmojiOne Color", 10F),
			new System.Drawing.Font("Enchanted Prairie Dog", 10F),
			new System.Drawing.Font("Encino", 10F),
			new System.Drawing.Font("English", 10F),
			new System.Drawing.Font("EngraversGothic BT", 10F),
			new System.Drawing.Font("Engrossing™", 10F),
			new System.Drawing.Font("EngrvrsOldEng BT", 10F),
			new System.Drawing.Font("Eras", 10F),
			new System.Drawing.Font("Esperanza™", 10F),
			new System.Drawing.Font("Estrangelo Edessa", 10F),
			new System.Drawing.Font("EucrosiaUPC", 10F),
			new System.Drawing.Font("Euphemia", 10F),
			new System.Drawing.Font("Excalibur Logotype", 10F),
			new System.Drawing.Font("Excalibur Monospace", 10F),
			new System.Drawing.Font("Excalibur Script", 10F),
			new System.Drawing.Font("Exocet", 10F),
			new System.Drawing.Font("Exocet Light ", 10F),
			new System.Drawing.Font("FangSong", 10F),
			new System.Drawing.Font("Fillmore", 10F),
			new System.Drawing.Font("First Grader", 10F),
			new System.Drawing.Font("FlemishScript BT", 10F),
			new System.Drawing.Font("Foxscript", 10F),
			new System.Drawing.Font("Frank Ruehl CLM", 10F),
			new System.Drawing.Font("Franklin Gothic", 10F),
			new System.Drawing.Font("Franklin Gothic Medium", 10F),
			new System.Drawing.Font("FrankRuehl", 10F),
			new System.Drawing.Font("Freefrm710 BT", 10F),
			new System.Drawing.Font("Freefrm721 Blk BT", 10F),
			new System.Drawing.Font("Freefrm721 BT", 10F),
			new System.Drawing.Font("Freehand521 BT", 10F),
			new System.Drawing.Font("Freehand575 BT", 10F),
			new System.Drawing.Font("Freehand591 BT", 10F),
			new System.Drawing.Font("FreesiaUPC", 10F),
			new System.Drawing.Font("Freestyle Script", 10F),
			new System.Drawing.Font("Fruity Drink", 10F),
			new System.Drawing.Font("Gabriel Regular Demo", 10F),
			new System.Drawing.Font("Gabriola", 10F),
			new System.Drawing.Font("Galaxia", 10F),
			new System.Drawing.Font("Gallery", 10F),
			new System.Drawing.Font("Gando BT", 10F),
			new System.Drawing.Font("Garamond", 10F),
			new System.Drawing.Font("Garamond Regular", 10F),
			new System.Drawing.Font("Gautami", 10F),
			new System.Drawing.Font("Gentium Basic", 10F),
			new System.Drawing.Font("Gentium Book Basic", 10F),
			new System.Drawing.Font("Georgia", 10F),
			new System.Drawing.Font("GeoSlab703 Lt BT", 10F),
			new System.Drawing.Font("Gill Sans Condensed", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("Gill Sans MT", 10F),
			new System.Drawing.Font("Gill Sans MT Condensed", 10F),
			new System.Drawing.Font("Gill Sans Ultra Bold", 10F),
			new System.Drawing.Font("Gill Sans Ultra Bold Condensed", 10F),
			new System.Drawing.Font("Gimbutas", 10F),
			new System.Drawing.Font("Girls are Weird", 10F),
			new System.Drawing.Font("Gisha", 10F),
			new System.Drawing.Font("Gismonda", 10F),
			new System.Drawing.Font("Gjallarhorn", 10F),
			new System.Drawing.Font("Glue", 10F),
			new System.Drawing.Font("Good Bad Ugly", 10F),
			new System.Drawing.Font("Goudy Old Style ATT", 10F),
			new System.Drawing.Font("Grail Light", 10F),
			new System.Drawing.Font("Graphic", 10F),
			new System.Drawing.Font("Graphite Light ATT", 10F),
			new System.Drawing.Font("Graphite Light Narrow ATT", 10F),
			new System.Drawing.Font("Griffin", 10F),
			new System.Drawing.Font("Gulim", 10F),
			new System.Drawing.Font("GulimChe", 10F),
			new System.Drawing.Font("Gungsuh", 10F),
			new System.Drawing.Font("GungsuhChe", 10F),
			new System.Drawing.Font("Hadrianus Demo", 10F),
			new System.Drawing.Font("Haettenschweiler", 10F),
			new System.Drawing.Font("Halloween", 10F),
			new System.Drawing.Font("Haman", 10F),
			new System.Drawing.Font("HandScript", 10F),
			new System.Drawing.Font("Harrington", 10F),
			new System.Drawing.Font("Head Case", 10F),
			new System.Drawing.Font("Hieroglify", 10F),
			new System.Drawing.Font("High Tower Text", 10F),
			new System.Drawing.Font("HighNoon", 10F),
			new System.Drawing.Font("Hooteroll", 10F),
			new System.Drawing.Font("Hooteroll_Jam", 10F),
			new System.Drawing.Font("Horse", 10F),
			new System.Drawing.Font("Humanst521 Cn BT", 10F),
			new System.Drawing.Font("Humanst521 Lt BT", 10F),
			new System.Drawing.Font("Iglesia-Light", 10F),
			new System.Drawing.Font("Ignacio", 10F),
			new System.Drawing.Font("Impact", 10F),
			new System.Drawing.Font("Impress BT", 10F),
			new System.Drawing.Font("Imprint MT Shadow", 10F),
			new System.Drawing.Font("Impuls BT", 10F),
			new System.Drawing.Font("Inspiration", 10F),
			new System.Drawing.Font("IrisUPC", 10F),
			new System.Drawing.Font("Iskoola Pota", 10F),
			new System.Drawing.Font("JasmineUPC", 10F),
			new System.Drawing.Font("Jellyka BeesAntique Handwriting", 10F),
			new System.Drawing.Font("Jellyka End_less Voyage", 10F),
			new System.Drawing.Font("Jellyka Saint-Andrew\'s Queen", 10F),
			new System.Drawing.Font("Jellyka Wonderland Wine", 10F),
			new System.Drawing.Font("Jolt", 10F),
			new System.Drawing.Font("Judas", 10F),
			new System.Drawing.Font("Juergen", 10F),
			new System.Drawing.Font("Jugend", 10F),
			new System.Drawing.Font("Juliet", 10F),
			new System.Drawing.Font("Junior & Stinky", 10F),
			new System.Drawing.Font("KacstBook", 10F),
			new System.Drawing.Font("KacstOffice", 10F),
			new System.Drawing.Font("KaiTi", 10F),
			new System.Drawing.Font("Kaligraf Latin", 10F),
			new System.Drawing.Font("Kalinga", 10F),
			new System.Drawing.Font("Kartika", 10F),
			new System.Drawing.Font("Kashmir", 10F),
			new System.Drawing.Font("Kaste", 10F),
			new System.Drawing.Font("Kastellar", 10F),
			new System.Drawing.Font("Keystrokes MT", 10F),
			new System.Drawing.Font("Khmer UI", 10F),
			new System.Drawing.Font("Klingon", 10F),
			new System.Drawing.Font("KodchiangUPC", 10F),
			new System.Drawing.Font("Kokila", 10F),
			new System.Drawing.Font("Kool", 10F),
			new System.Drawing.Font("Kroeburn", 10F),
			new System.Drawing.Font("Lao UI", 10F),
			new System.Drawing.Font("LaPointe\'s Road", 10F),
			new System.Drawing.Font("Last Ninja", 10F),
			new System.Drawing.Font("Latha", 10F),
			new System.Drawing.Font("Leelawadee", 10F),
			new System.Drawing.Font("Letter Gothic Line", 10F),
			new System.Drawing.Font("Letterman-Solid", 10F),
			new System.Drawing.Font("Levenim MT", 10F),
			new System.Drawing.Font("Liberation Mono", 10F),
			new System.Drawing.Font("Liberation Sans", 10F),
			new System.Drawing.Font("Liberation Sans Narrow", 10F),
			new System.Drawing.Font("Liberation Serif", 10F),
			new System.Drawing.Font("Libra BT", 10F),
			new System.Drawing.Font("Librarian", 10F),
			new System.Drawing.Font("Liddie Black", 10F),
			new System.Drawing.Font("Lights", 10F),
			new System.Drawing.Font("LilyUPC", 10F),
			new System.Drawing.Font("Linux Biolinum G", 10F),
			new System.Drawing.Font("Linux Libertine Display G", 10F),
			new System.Drawing.Font("Linux Libertine G", 10F),
			new System.Drawing.Font("LLUmbrian", 10F),
			new System.Drawing.Font("LLVenetic", 10F),
			new System.Drawing.Font("Loki Cola", 10F),
			new System.Drawing.Font("LotusWP Box", 10F),
			new System.Drawing.Font("LotusWP Icon", 10F),
			new System.Drawing.Font("LotusWP Int A", 10F),
			new System.Drawing.Font("LotusWP Int B", 10F),
			new System.Drawing.Font("LotusWP Type", 10F),
			new System.Drawing.Font("Lucida Blacklet", 10F),
			new System.Drawing.Font("Lucida Calligraphy", 10F),
			new System.Drawing.Font("Lucida Console", 10F),
			new System.Drawing.Font("Lucida Sans Unicode", 10F),
			new System.Drawing.Font("Luxembourg", 10F),
			new System.Drawing.Font("Machiavelli", 10F),
			new System.Drawing.Font("MacHumaine", 10F),
			new System.Drawing.Font("Magik", 10F),
			new System.Drawing.Font("Maiandra GD", 10F),
			new System.Drawing.Font("Malgun Gothic", 10F),
			new System.Drawing.Font("Mangal", 10F),
			new System.Drawing.Font("Maple Serum", 10F),
			new System.Drawing.Font("Mapmaker Thin", 10F),
			new System.Drawing.Font("MarkerFeltThin", 10F),
			new System.Drawing.Font("MarkerFeltWide-Plain", 10F),
			new System.Drawing.Font("Marlett", 10F),
			new System.Drawing.Font("Marquee", 10F),
			new System.Drawing.Font("Matura MT Script Capitals", 10F),
			new System.Drawing.Font("Mcgannahan", 10F),
			new System.Drawing.Font("Medusa", 10F),
			new System.Drawing.Font("Meet John Henry", 10F),
			new System.Drawing.Font("Meiryo", 10F),
			new System.Drawing.Font("Meiryo UI", 10F),
			new System.Drawing.Font("Men In Black Credits", 10F),
			new System.Drawing.Font("Mephisto™", 10F),
			new System.Drawing.Font("Microsoft Himalaya", 10F),
			new System.Drawing.Font("Microsoft JhengHei", 10F),
			new System.Drawing.Font("Microsoft New Tai Lue", 10F),
			new System.Drawing.Font("Microsoft PhagsPa", 10F),
			new System.Drawing.Font("Microsoft Sans Serif", 10F),
			new System.Drawing.Font("Microsoft Tai Le", 10F),
			new System.Drawing.Font("Microsoft Uighur", 10F),
			new System.Drawing.Font("Microsoft YaHei", 10F),
			new System.Drawing.Font("Microsoft Yi Baiti", 10F),
			new System.Drawing.Font("MingLiU", 10F),
			new System.Drawing.Font("MingLiU-ExtB", 10F),
			new System.Drawing.Font("MingLiU_HKSCS", 10F),
			new System.Drawing.Font("MingLiU_HKSCS-ExtB", 10F),
			new System.Drawing.Font("Minstrel Script", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("Miriam", 10F),
			new System.Drawing.Font("Miriam CLM", 10F),
			new System.Drawing.Font("Miriam Fixed", 10F),
			new System.Drawing.Font("Miriam Mono CLM", 10F),
			new System.Drawing.Font("MisterEarl BT", 10F),
			new System.Drawing.Font("Mitzvah", 10F),
			new System.Drawing.Font("Monaco", 10F),
			new System.Drawing.Font("Mongolian Baiti", 10F),
			new System.Drawing.Font("Monkey Chunks", 10F),
			new System.Drawing.Font("Monotype Sorts", 10F),
			new System.Drawing.Font("MoolBoran", 10F),
			new System.Drawing.Font("Mordred", 10F),
			new System.Drawing.Font("More Enchanted Prairie Dog", 10F),
			new System.Drawing.Font("Morpheus", 10F),
			new System.Drawing.Font("MS Gothic", 10F),
			new System.Drawing.Font("MS Mincho", 10F),
			new System.Drawing.Font("MS Outlook", 10F),
			new System.Drawing.Font("MS PGothic", 10F),
			new System.Drawing.Font("MS PMincho", 10F),
			new System.Drawing.Font("MS UI Gothic", 10F),
			new System.Drawing.Font("Mutlu", 10F),
			new System.Drawing.Font("MV Boli", 10F),
			new System.Drawing.Font("Narkisim", 10F),
			new System.Drawing.Font("Nauert", 10F),
			new System.Drawing.Font("Neone", 10F),
			new System.Drawing.Font("Neverwinter", 10F),
			new System.Drawing.Font("Nite", 10F),
			new System.Drawing.Font("Nixon", 10F),
			new System.Drawing.Font("Nosfer", 10F),
			new System.Drawing.Font("Nosferatu", 10F, System.Drawing.FontStyle.Italic),
			new System.Drawing.Font("Nosferotica", 10F),
			new System.Drawing.Font("Noto Kufi Arabic", 10F),
			new System.Drawing.Font("Noto Mono", 10F),
			new System.Drawing.Font("Noto Naskh Arabic", 10F),
			new System.Drawing.Font("Noto Naskh Arabic UI", 10F),
			new System.Drawing.Font("Noto Sans", 10F),
			new System.Drawing.Font("Noto Sans Arabic", 10F),
			new System.Drawing.Font("Noto Sans Arabic UI", 10F),
			new System.Drawing.Font("Noto Sans Armenian", 10F),
			new System.Drawing.Font("Noto Sans Cond", 10F),
			new System.Drawing.Font("Noto Sans Georgian", 10F),
			new System.Drawing.Font("Noto Sans Hebrew", 10F),
			new System.Drawing.Font("Noto Sans Lao", 10F),
			new System.Drawing.Font("Noto Sans Light", 10F),
			new System.Drawing.Font("Noto Sans Lisu", 10F),
			new System.Drawing.Font("Noto Serif", 10F),
			new System.Drawing.Font("Noto Serif Armenian", 10F),
			new System.Drawing.Font("Noto Serif Cond", 10F),
			new System.Drawing.Font("Noto Serif Georgian", 10F),
			new System.Drawing.Font("Noto Serif Hebrew", 10F),
			new System.Drawing.Font("Noto Serif Lao", 10F),
			new System.Drawing.Font("Noto Serif Light", 10F),
			new System.Drawing.Font("Nouveau", 10F),
			new System.Drawing.Font("NSimSun", 10F),
			new System.Drawing.Font("Nuptial BT", 10F),
			new System.Drawing.Font("Nyala", 10F),
			new System.Drawing.Font("OFL Sorts Mill Goudy TT", 10F),
			new System.Drawing.Font("Ogilvie", 10F),
			new System.Drawing.Font("Old English Gothic", 10F),
			new System.Drawing.Font("Old printing press_FREE-version", 10F),
			new System.Drawing.Font("Olde English", 10F),
			new System.Drawing.Font("Onyx BT", 10F),
			new System.Drawing.Font("Open Sans", 10F),
			new System.Drawing.Font("OpenSymbol", 10F),
			new System.Drawing.Font("OptimusPrinceps", 10F),
			new System.Drawing.Font("OptimusPrincepsSemiBold", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("Oscan", 10F),
			new System.Drawing.Font("OzHandicraft BT", 10F),
			new System.Drawing.Font("P", 10F),
			new System.Drawing.Font("Palatia", 10F),
			new System.Drawing.Font("Palatino Linotype", 10F),
			new System.Drawing.Font("Paramount", 10F),
			new System.Drawing.Font("Paris", 10F),
			new System.Drawing.Font("Patrician™", 10F),
			new System.Drawing.Font("PCMIra", 10F),
			new System.Drawing.Font("Peace", 10F),
			new System.Drawing.Font("Penyae", 10F),
			new System.Drawing.Font("Piranesi It BT", 10F),
			new System.Drawing.Font("Plantagenet Cherokee", 10F),
			new System.Drawing.Font("Platthand Demo", 10F),
			new System.Drawing.Font("Plok", 10F),
			new System.Drawing.Font("PMingLiU", 10F),
			new System.Drawing.Font("PMingLiU-ExtB", 10F),
			new System.Drawing.Font("Poison Dots", 10F),
			new System.Drawing.Font("Poke", 10F),
			new System.Drawing.Font("Poncho", 10F),
			new System.Drawing.Font("PonchoVia-Light", 10F),
			new System.Drawing.Font("Pontifica Demo", 10F),
			new System.Drawing.Font("PotsDam", 10F),
			new System.Drawing.Font("Powderworks BRK", 10F),
			new System.Drawing.Font("Present-Normal", 10F),
			new System.Drawing.Font("Priory", 10F),
			new System.Drawing.Font("Promenade", 10F),
			new System.Drawing.Font("Pseudolux", 10F),
			new System.Drawing.Font("Psychadelic", 10F),
			new System.Drawing.Font("PT Serif", 10F),
			new System.Drawing.Font("Pyxidium Quick", 10F),
			new System.Drawing.Font("Quantity", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("QuartetBold", 10F),
			new System.Drawing.Font("QuartetRegular", 10F),
			new System.Drawing.Font("Quetzal Demo", 10F),
			new System.Drawing.Font("Raavi", 10F),
			new System.Drawing.Font("Radius", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("Reed", 10F),
			new System.Drawing.Font("Reem Kufi", 10F),
			new System.Drawing.Font("Ribbon131 Bd BT", 10F),
			new System.Drawing.Font("Rickshaw", 10F),
			new System.Drawing.Font("Rod", 10F),
			new System.Drawing.Font("Rogers", 10F),
			new System.Drawing.Font("Roman Stonecut", 10F),
			new System.Drawing.Font("Romeodn", 10F),
			new System.Drawing.Font("RoostHeavy", 10F),
			new System.Drawing.Font("Roughwork Demo", 10F),
			new System.Drawing.Font("Rounders", 10F),
			new System.Drawing.Font("Rubik", 10F),
			new System.Drawing.Font("Rudelsberg", 10F),
			new System.Drawing.Font("Sakkal Majalla", 10F),
			new System.Drawing.Font("SANTOS DUMONT", 10F),
			new System.Drawing.Font("Sanvito", 10F, System.Drawing.FontStyle.Italic),
			new System.Drawing.Font("Scheherazade", 10F),
			new System.Drawing.Font("Schoolbook", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("SchoolBoy", 10F),
			new System.Drawing.Font("Science Project", 10F),
			new System.Drawing.Font("Scriptina", 10F),
			new System.Drawing.Font("Scriptina - Alternates", 10F),
			new System.Drawing.Font("Seagull Lt BT", 10F),
			new System.Drawing.Font("Seagull Md BT", 10F),
			new System.Drawing.Font("Segoe Print", 10F),
			new System.Drawing.Font("Segoe Script", 10F),
			new System.Drawing.Font("Segoe UI", 10F),
			new System.Drawing.Font("Segoe UI Light", 10F),
			new System.Drawing.Font("Segoe UI Semibold", 10F),
			new System.Drawing.Font("Segoe UI Symbol", 10F),
			new System.Drawing.Font("Seven Swordsmen BB", 10F),
			new System.Drawing.Font("Sexy Silouette Stencils", 10F),
			new System.Drawing.Font("SEXY SPANISH ERASMUS GIRLS V.2.", 10F),
			new System.Drawing.Font("SEXY_SPANISH_WOMAN", 10F),
			new System.Drawing.Font("ShelleyAllegro BT", 10F),
			new System.Drawing.Font("ShelleyAndante BT", 10F),
			new System.Drawing.Font("ShelleyVolante BT", 10F),
			new System.Drawing.Font("Sherwood", 10F),
			new System.Drawing.Font("Shonar Bangla", 10F),
			new System.Drawing.Font("Shruti", 10F),
			new System.Drawing.Font("SimHei", 10F),
			new System.Drawing.Font("Simplified Arabic", 10F),
			new System.Drawing.Font("Simplified Arabic Fixed", 10F),
			new System.Drawing.Font("SimSun", 10F),
			new System.Drawing.Font("SimSun-ExtB", 10F),
			new System.Drawing.Font("Sinaloa", 10F),
			new System.Drawing.Font("Singothic", 10F),
			new System.Drawing.Font("Smegalomania", 10F),
			new System.Drawing.Font("Snell BT", 10F),
			new System.Drawing.Font("Source Code Pro", 10F),
			new System.Drawing.Font("Source Code Pro Black", 10F),
			new System.Drawing.Font("Source Code Pro ExtraLight", 10F),
			new System.Drawing.Font("Source Code Pro Light", 10F),
			new System.Drawing.Font("Source Code Pro Medium", 10F),
			new System.Drawing.Font("Source Code Pro Semibold", 10F),
			new System.Drawing.Font("Source Sans Pro", 10F),
			new System.Drawing.Font("Source Sans Pro Black", 10F),
			new System.Drawing.Font("Source Sans Pro ExtraLight", 10F),
			new System.Drawing.Font("Source Sans Pro Light", 10F),
			new System.Drawing.Font("Source Sans Pro Semibold", 10F),
			new System.Drawing.Font("Stencil", 10F),
			new System.Drawing.Font("Stencil-Normal", 10F),
			new System.Drawing.Font("Stencilcase", 10F),
			new System.Drawing.Font("Stinger", 10F),
			new System.Drawing.Font("Stonecross", 10F),
			new System.Drawing.Font("Stonehenge", 10F),
			new System.Drawing.Font("Styletto", 10F),
			new System.Drawing.Font("Sumdumgoi", 10F),
			new System.Drawing.Font("Swis721 BlkEx BT", 10F),
			new System.Drawing.Font("Sylfaen", 10F),
			new System.Drawing.Font("Symbol", 10F),
			new System.Drawing.Font("Tahoma", 10F),
			new System.Drawing.Font("Tango", 10F),
			new System.Drawing.Font("Tapestry", 10F),
			new System.Drawing.Font("Tarantis", 10F),
			new System.Drawing.Font("Tempo", 10F),
			new System.Drawing.Font("Tempus", 10F),
			new System.Drawing.Font("Tengwar Cursive", 10F),
			new System.Drawing.Font("Tengwar Noldor", 10F),
			new System.Drawing.Font("Tengwar Noldor-1", 10F),
			new System.Drawing.Font("Tengwar Noldor-2", 10F),
			new System.Drawing.Font("Tengwar Noldor-A", 10F),
			new System.Drawing.Font("Tengwar Parmaite", 10F),
			new System.Drawing.Font("Tengwar Quenya", 10F),
			new System.Drawing.Font("Tengwar Quenya-1", 10F),
			new System.Drawing.Font("Tengwar Quenya-2", 10F),
			new System.Drawing.Font("Tengwar Quenya-A", 10F),
			new System.Drawing.Font("Tengwar Sindarin", 10F),
			new System.Drawing.Font("Tengwar Sindarin-1", 10F),
			new System.Drawing.Font("Tengwar Sindarin-2", 10F),
			new System.Drawing.Font("Tengwar Sindarin-A", 10F),
			new System.Drawing.Font("Tengwar-Gandalf", 10F),
			new System.Drawing.Font("Terpsichore™", 10F),
			new System.Drawing.Font("Thalia", 10F),
			new System.Drawing.Font("the King & Queen font", 10F),
			new System.Drawing.Font("This is not a font", 10F),
			new System.Drawing.Font("Thorass", 10F),
			new System.Drawing.Font("Times New Roman", 10F),
			new System.Drawing.Font("Totem", 10F),
			new System.Drawing.Font("ToulouseLautrec", 10F),
			new System.Drawing.Font("Traditional Arabic", 10F),
			new System.Drawing.Font("Trebuchet MS", 10F),
			new System.Drawing.Font("Tribune", 10F),
			new System.Drawing.Font("True Stories", 10F),
			new System.Drawing.Font("TrumpetLite", 10F),
			new System.Drawing.Font("Tunga", 10F),
			new System.Drawing.Font("Turkey Sandwich", 10F),
			new System.Drawing.Font("Typewriter", 10F),
			new System.Drawing.Font("Uncials", 10F),
			new System.Drawing.Font("Unispace", 10F, System.Drawing.FontStyle.Bold),
			new System.Drawing.Font("University", 10F),
			new System.Drawing.Font("UniversityRoman", 10F),
			new System.Drawing.Font("Unserif", 10F),
			new System.Drawing.Font("Upper-EastSide", 10F),
			new System.Drawing.Font("Urban Scrawl Chill", 10F),
			new System.Drawing.Font("Urban Scrawl Down", 10F),
			new System.Drawing.Font("Urban Scrawl-Buttah", 10F),
			new System.Drawing.Font("ureka", 10F),
			new System.Drawing.Font("Utsaah", 10F),
			new System.Drawing.Font("Valdemar", 10F),
			new System.Drawing.Font("Vani", 10F),
			new System.Drawing.Font("Vein", 10F),
			new System.Drawing.Font("Verdana", 10F),
			new System.Drawing.Font("Verticalization", 10F),
			new System.Drawing.Font("Vespasiano Demo", 10F),
			new System.Drawing.Font("Victorias-Secre", 10F),
			new System.Drawing.Font("Vijaya", 10F),
			new System.Drawing.Font("Viking", 10F),
			new System.Drawing.Font("Violation", 10F),
			new System.Drawing.Font("Vireo", 10F),
			new System.Drawing.Font("Vrinda", 10F),
			new System.Drawing.Font("Wanted Poster", 10F),
			new System.Drawing.Font("Webdings", 10F),
			new System.Drawing.Font("WeddingText BT", 10F),
			new System.Drawing.Font("Weirdo Warp", 10F),
			new System.Drawing.Font("Weiss", 10F),
			new System.Drawing.Font("Windsong", 10F),
			new System.Drawing.Font("Wingdings", 10F),
			new System.Drawing.Font("Xirwena", 10F),
			new System.Drawing.Font("Yataghan", 10F),
			new System.Drawing.Font("Zygoth", 10F),
			new System.Drawing.Font("Zyme", 10F, System.Drawing.FontStyle.Italic)});
			this.list_Font.Location = new System.Drawing.Point(5, 20);
			this.list_Font.Name = "list_Font";
			this.list_Font.Size = new System.Drawing.Size(225, 264);
			this.list_Font.TabIndex = 6;
			this.list_Font.DrawItem += new System.Windows.Forms.DrawItemEventHandler(this.fontList_DrawItem);
			this.list_Font.SelectedIndexChanged += new System.EventHandler(this.fontList_SelectedIndexChanged);
			// 
			// btn_Ok
			// 
			this.btn_Ok.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
			| System.Windows.Forms.AnchorStyles.Right)));
			this.btn_Ok.Location = new System.Drawing.Point(5, 5);
			this.btn_Ok.Name = "btn_Ok";
			this.btn_Ok.Size = new System.Drawing.Size(208, 35);
			this.btn_Ok.TabIndex = 0;
			this.btn_Ok.Text = "ok";
			this.btn_Ok.UseVisualStyleBackColor = true;
			this.btn_Ok.Click += new System.EventHandler(this.btnOk_click);
			// 
			// btn_Apply
			// 
			this.btn_Apply.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
			| System.Windows.Forms.AnchorStyles.Right)));
			this.btn_Apply.Location = new System.Drawing.Point(5, 45);
			this.btn_Apply.Name = "btn_Apply";
			this.btn_Apply.Size = new System.Drawing.Size(206, 35);
			this.btn_Apply.TabIndex = 1;
			this.btn_Apply.Text = "apply";
			this.btn_Apply.UseVisualStyleBackColor = true;
			this.btn_Apply.Click += new System.EventHandler(this.btnApply_click);
			// 
			// btn_Cancel
			// 
			this.btn_Cancel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
			| System.Windows.Forms.AnchorStyles.Right)));
			this.btn_Cancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
			this.btn_Cancel.Location = new System.Drawing.Point(5, 85);
			this.btn_Cancel.Name = "btn_Cancel";
			this.btn_Cancel.Size = new System.Drawing.Size(208, 35);
			this.btn_Cancel.TabIndex = 2;
			this.btn_Cancel.Text = "cancel";
			this.btn_Cancel.UseVisualStyleBackColor = true;
			this.btn_Cancel.Click += new System.EventHandler(this.btnCancel_click);
			// 
			// lbl_Font
			// 
			this.lbl_Font.Location = new System.Drawing.Point(10, 5);
			this.lbl_Font.Name = "lbl_Font";
			this.lbl_Font.Size = new System.Drawing.Size(220, 15);
			this.lbl_Font.TabIndex = 3;
			this.lbl_Font.Text = "FONT";
			// 
			// lbl_Style
			// 
			this.lbl_Style.Location = new System.Drawing.Point(245, 10);
			this.lbl_Style.Name = "lbl_Style";
			this.lbl_Style.Size = new System.Drawing.Size(80, 15);
			this.lbl_Style.TabIndex = 4;
			this.lbl_Style.Text = "Style";
			// 
			// lbl_Size
			// 
			this.lbl_Size.Location = new System.Drawing.Point(290, 85);
			this.lbl_Size.Name = "lbl_Size";
			this.lbl_Size.Size = new System.Drawing.Size(35, 15);
			this.lbl_Size.TabIndex = 5;
			this.lbl_Size.Text = "pt";
			// 
			// list_Style
			// 
			this.list_Style.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
			this.list_Style.FormattingEnabled = true;
			this.list_Style.ItemHeight = 15;
			this.list_Style.Location = new System.Drawing.Point(240, 25);
			this.list_Style.Name = "list_Style";
			this.list_Style.Size = new System.Drawing.Size(85, 49);
			this.list_Style.TabIndex = 7;
			this.list_Style.DrawItem += new System.Windows.Forms.DrawItemEventHandler(this.styleList_DrawItem);
			this.list_Style.SelectedIndexChanged += new System.EventHandler(this.fontStyle_SelectedIndexChanged);
			// 
			// list_Size
			// 
			this.list_Size.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
			this.list_Size.FormattingEnabled = true;
			this.list_Size.ItemHeight = 15;
			this.list_Size.Location = new System.Drawing.Point(240, 85);
			this.list_Size.Name = "list_Size";
			this.list_Size.Size = new System.Drawing.Size(40, 199);
			this.list_Size.TabIndex = 8;
			this.list_Size.DrawItem += new System.Windows.Forms.DrawItemEventHandler(this.sizeList_DrawItem);
			this.list_Size.SelectedIndexChanged += new System.EventHandler(this.fontSize_SelectedIndexChanged);
			// 
			// lbl_Example
			// 
			this.lbl_Example.Dock = System.Windows.Forms.DockStyle.Bottom;
			this.lbl_Example.Location = new System.Drawing.Point(0, 290);
			this.lbl_Example.Name = "lbl_Example";
			this.lbl_Example.Padding = new System.Windows.Forms.Padding(5, 0, 5, 0);
			this.lbl_Example.Size = new System.Drawing.Size(553, 111);
			this.lbl_Example.TabIndex = 10;
			// 
			// tb_Size
			// 
			this.tb_Size.Location = new System.Drawing.Point(285, 105);
			this.tb_Size.Name = "tb_Size";
			this.tb_Size.Size = new System.Drawing.Size(40, 20);
			this.tb_Size.TabIndex = 11;
			this.tb_Size.TextChanged += new System.EventHandler(this.fontSize_TextChanged);
			// 
			// panel1
			// 
			this.panel1.Controls.Add(this.btn_Ok);
			this.panel1.Controls.Add(this.btn_Apply);
			this.panel1.Controls.Add(this.btn_Cancel);
			this.panel1.Dock = System.Windows.Forms.DockStyle.Right;
			this.panel1.Location = new System.Drawing.Point(335, 0);
			this.panel1.Name = "panel1";
			this.panel1.Size = new System.Drawing.Size(218, 290);
			this.panel1.TabIndex = 12;
			// 
			// FontPickerForm
			// 
			this.AcceptButton = this.btn_Ok;
			this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 14F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.CancelButton = this.btn_Cancel;
			this.ClientSize = new System.Drawing.Size(553, 401);
			this.Controls.Add(this.panel1);
			this.Controls.Add(this.tb_Size);
			this.Controls.Add(this.lbl_Example);
			this.Controls.Add(this.list_Size);
			this.Controls.Add(this.list_Style);
			this.Controls.Add(this.list_Font);
			this.Controls.Add(this.lbl_Size);
			this.Controls.Add(this.lbl_Style);
			this.Controls.Add(this.lbl_Font);
			this.Font = new System.Drawing.Font("Georgia", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.Name = "FontPickerForm";
			this.SizeGripStyle = System.Windows.Forms.SizeGripStyle.Hide;
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Choose Font";
			this.panel1.ResumeLayout(false);
			this.ResumeLayout(false);
			this.PerformLayout();

		}
	}
}
